### Перед запуском нужно создать админа через scripts.py

### Создание user_1 (id = 2)
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "John",
  "password": "123456"
}

### Создание user_2 (id = 3)
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "Doe",
  "password": "654321"
}


### Токен админа: ea2fab94-a7ad-4c6b-ade1-a51a8ad0e0e9
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"
}

###  Токен user_1: f2049dc9-9183-4ef8-80c9-c4603e1ce08f
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "John",
  "password": "123456"
}

### Токен user_2: 1501cd85-435e-4c4b-aaf6-5fb37e62821d
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "Doe",
  "password": "654321"
}



### Попытка создания объявления без токен
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json

{
  "title": "First advertisement",
  "description": "First description",
  "price": 10.455
}

### Создание объявления с токеном user_1
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json
x-token: f2049dc9-9183-4ef8-80c9-c4603e1ce08f

{
  "title": "First advertisement",
  "description": "First description",
  "price": 10.455
}

### Создание объявления с токеном user_2
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json
x-token: 1501cd85-435e-4c4b-aaf6-5fb37e62821d

{
  "title": "Second advertisement",
  "description": "Second description",
  "price": 1123
}

### Получение объявления без токена
GET http://localhost:8080/api/v1/advertisement/1

### Получение всех объявлений без токена
GET http://localhost:8080/api/v1/advertisement

### Получение объявления по фильтру без токена
GET http://localhost:8080/api/v1/advertisement?title=First advertisement&description=First description&price=10.455




### Обновление объявления без токена
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json

{
  "title": "New title"
}

### Обновление объявления user_1 с токеном user_2
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json
x-Token: 1501cd85-435e-4c4b-aaf6-5fb37e62821d

{
  "title": "New title by user_2"
}

### Обновление объявления user_1 с токеном user_1
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json
x-token: f2049dc9-9183-4ef8-80c9-c4603e1ce08f

{
  "title": "New title by user_1"
}

### Проверка изменения объявления
GET http://localhost:8080/api/v1/advertisement/1

### Обновление объявления user_2 с токеном админа
PATCH http://localhost:8080/api/v1/advertisement/2
Content-Type: application/json
x-token: ea2fab94-a7ad-4c6b-ade1-a51a8ad0e0e9

{
  "title": "New title by admin"
}

### Проверка изменения объявления
GET http://localhost:8080/api/v1/advertisement/2



### Удаление объявления без токена
DELETE http://localhost:8080/api/v1/advertisement/1

### Удаление объявления user_2 с токеном user_1
DELETE http://localhost:8080/api/v1/advertisement/2
x-token: f2049dc9-9183-4ef8-80c9-c4603e1ce08f

### Удаление объявления user_2 с токеном user_2
DELETE http://localhost:8080/api/v1/advertisement/2
x-token: 1501cd85-435e-4c4b-aaf6-5fb37e62821d

### Получение всех объявлений
GET http://localhost:8080/api/v1/advertisement

### Удаление объявления user_1 с токеном админа
DELETE http://localhost:8080/api/v1/advertisement/1
x-token: ea2fab94-a7ad-4c6b-ade1-a51a8ad0e0e9

### Получение всех объявлений
GET http://localhost:8080/api/v1/advertisement



### Получение user_1
GET http://localhost:8080/api/v1/user/2

### Обновление user_1 без токена
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json

{
  "name": "New name without token"
}

### Обновление user_1 с токеном user_2
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json
x-token: 1501cd85-435e-4c4b-aaf6-5fb37e62821d

{
  "name": "New name by user_2"
}

### Обновление user_1 с токеном user_1 с ролью
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json
x-token: f2049dc9-9183-4ef8-80c9-c4603e1ce08f

{
  "name": "New name by user_1 with new role",
  "role": "admin"
}

### Обновление user_1 с токеном user_1
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json
x-token: f2049dc9-9183-4ef8-80c9-c4603e1ce08f

{
  "name": "New name by user_1"
}
### Проверка изменения user_1
GET http://localhost:8080/api/v1/user/2

### Удаление user_1 с токеном user_2
DELETE http://localhost:8080/api/v1/user/2
x-token: 1501cd85-435e-4c4b-aaf6-5fb37e62821d

### Удаление user_1 с токеном user_1
DELETE http://localhost:8080/api/v1/user/2
x-token: f2049dc9-9183-4ef8-80c9-c4603e1ce08f

### Получение user_1
GET http://localhost:8080/api/v1/user/2

### Обновление user_2 с токеном админа
PATCH http://localhost:8080/api/v1/user/3
Content-Type: application/json
x-token: ea2fab94-a7ad-4c6b-ade1-a51a8ad0e0e9

{
  "name": "New name by admin",
  "role": "admin"
}

### Получение user_2
GET http://localhost:8080/api/v1/user/3

### Создание user_3
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "New user",
  "password": "123456"
}

### Обновление user_3 с токеном user_2 (admin)
PATCH http://localhost:8080/api/v1/user/4
Content-Type: application/json
x-token: 1501cd85-435e-4c4b-aaf6-5fb37e62821d

{
  "name": "New name by user_2"
}

### Получение user_3
GET http://localhost:8080/api/v1/user/4
