### Создание user_1
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "John",
  "password": "123456"
}

### Создание user_2
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "Doe",
  "password": "654321"
}

###  Токен user_1: 86706c3e-7cfb-47cf-88d0-7625022a3bbd
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "John",
  "password": "123456"
}

### Токен user_2: db22f726-60d7-4e7f-8379-2480e7985f07
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "Doe",
  "password": "654321"
}

### Попытка создания объявления без токен
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json

{
  "title": "First advertisement",
  "description": "First description",
  "price": 10.455
}

### Создание объявления с токеном user_1
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json
x-token: 86706c3e-7cfb-47cf-88d0-7625022a3bbd

{
  "title": "First advertisement",
  "description": "First description",
  "price": 10.455
}

### Создание объявления с токеном user_2
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json
x-token: db22f726-60d7-4e7f-8379-2480e7985f07

{
  "title": "Second advertisement",
  "description": "Second description",
  "price": 1123
}

### Получение всех объявлений
GET http://localhost:8080/api/v1/advertisement

### Обновление объявления без токена
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json

{
  "title": "New title"
}

### Обновление объявления user_1 с токеном user_2
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json
x-Token: db22f726-60d7-4e7f-8379-2480e7985f07

{
  "title": "New title"
}

### Обновление объявления user_1 с токеном user_1
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json
x-token: 86706c3e-7cfb-47cf-88d0-7625022a3bbd

{
  "title": "New title"
}

### Проверка изменения объявления
GET http://localhost:8080/api/v1/advertisement/1

### Удаление объявления без токена
DELETE http://localhost:8080/api/v1/advertisement/2

### Удаление объявления user_2 с токеном user_1
DELETE http://localhost:8080/api/v1/advertisement/2
x-token: 86706c3e-7cfb-47cf-88d0-7625022a3bbd

### Удаление объявления user_2 с токеном user_2
DELETE http://localhost:8080/api/v1/advertisement/2
x-token: db22f726-60d7-4e7f-8379-2480e7985f07

### Получение всех объявлений
GET http://localhost:8080/api/v1/advertisement
