### Перед запуском нужно создать админа через scripts.py

### Создание user_1 (id = 2)
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "John",
  "password": "123456"
}

### Создание user_2 (id = 3)
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "Doe",
  "password": "654321"
}


### Токен админа: 6e04d572-7000-41f1-bb98-1bef0750e055
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"
}

###  Токен user_1: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "John",
  "password": "123456"
}

### Токен user_2: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "name": "Doe",
  "password": "654321"
}



### Попытка создания объявления без токен
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json

{
  "title": "First advertisement",
  "description": "First description",
  "price": 10.455
}

### Создание объявления с токеном user_1
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json
x-token: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c

{
  "title": "First advertisement",
  "description": "First description",
  "price": 10.455
}

### Создание объявления с токеном user_2
POST http://localhost:8080/api/v1/advertisement
Content-Type: application/json
x-token: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00

{
  "title": "Second advertisement",
  "description": "Second description",
  "price": 1123
}

### Получение объявления без токена
GET http://localhost:8080/api/v1/advertisement/1

### Получение всех объявлений без токена
GET http://localhost:8080/api/v1/advertisement

### Получение объявления по фильтру без токена
GET http://localhost:8080/api/v1/advertisement?title=First advertisement&description=First description&price=10.455




### Обновление объявления без токена
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json

{
  "title": "New title"
}

### Обновление объявления user_1 с токеном user_2
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json
x-Token: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00

{
  "title": "New title by user_2"
}

### Обновление объявления user_1 с токеном user_1
PATCH http://localhost:8080/api/v1/advertisement/1
Content-Type: application/json
x-token: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c

{
  "title": "New title by user_1"
}

### Проверка изменения объявления
GET http://localhost:8080/api/v1/advertisement/1

### Обновление объявления user_2 с токеном админа
PATCH http://localhost:8080/api/v1/advertisement/2
Content-Type: application/json
x-token: 6e04d572-7000-41f1-bb98-1bef0750e055

{
  "title": "New title by admin"
}

### Проверка изменения объявления
GET http://localhost:8080/api/v1/advertisement/2



### Удаление объявления без токена
DELETE http://localhost:8080/api/v1/advertisement/1

### Удаление объявления user_2 с токеном user_1
DELETE http://localhost:8080/api/v1/advertisement/2
x-token: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c

### Удаление объявления user_2 с токеном user_2
DELETE http://localhost:8080/api/v1/advertisement/2
x-token: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00

### Получение всех объявлений
GET http://localhost:8080/api/v1/advertisement

### Удаление объявления user_1 с токеном админа
DELETE http://localhost:8080/api/v1/advertisement/1
x-token: 6e04d572-7000-41f1-bb98-1bef0750e055

### Получение всех объявлений
GET http://localhost:8080/api/v1/advertisement



### Получение user_1
GET http://localhost:8080/api/v1/user/2

### Обновление user_1 без токена
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json

{
  "name": "New name without token"
}

### Обновление user_1 с токеном user_2
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json
x-token: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00

{
  "name": "New name by user_2"
}

### Обновление user_1 с токеном user_1 с ролью
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json
x-token: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c

{
  "name": "New name by user_1 with new role",
  "role": "admin"
}

### Обновление user_1 с токеном user_1
PATCH http://localhost:8080/api/v1/user/2
Content-Type: application/json
x-token: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c

{
  "name": "New name by user_1"
}
### Проверка изменения user_1
GET http://localhost:8080/api/v1/user/2

### Удаление user_1 с токеном user_2
DELETE http://localhost:8080/api/v1/user/2
x-token: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00

### Удаление user_1 с токеном user_1
DELETE http://localhost:8080/api/v1/user/2
x-token: d8dbc31c-fdd6-4bcf-ace1-e7d04c902f5c

### Получение user_1
GET http://localhost:8080/api/v1/user/2

### Обновление user_2 с токеном админа
PATCH http://localhost:8080/api/v1/user/3
Content-Type: application/json
x-token: 6e04d572-7000-41f1-bb98-1bef0750e055

{
  "name": "New name by admin",
  "role": "admin"
}

### Получение user_2
GET http://localhost:8080/api/v1/user/3

### Создание user_3
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "name": "New user",
  "password": "123456"
}

### Обновление user_3 с токеном user_2 (admin)
PATCH http://localhost:8080/api/v1/user/4
Content-Type: application/json
x-token: 23ceeba8-57d9-4b5d-85eb-a94f27f7bf00

{
  "name": "New name by user_2"
}

### Получение user_3
GET http://localhost:8080/api/v1/user/4
